# Generated by Django 6.0 on 2025-12-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_idempotencykey_unique_idempotency_key_per_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idempotencykey',
            name='key',
            field=models.CharField(max_length=255),
        ),
    ]
